#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/yujinrobot/yujin_ocs/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import rospy
import yocs_ar_pair_approach
import threading

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':

    rospy.init_node('test_rotate')
    rotate = yocs_ar_pair_approach.Rotate('/cmd_vel')
    thread = threading.Thread(target=rotate.execute)
    thread.start()
    rospy.sleep(3.0)
    rotate.change_direction()
    rospy.sleep(3.0)
    rotate.change_direction()
    rospy.sleep(3.0)
    rotate.stop()
